version: "3.5"
services:
  broker:
    image: broker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PIVEAU_HUB_HOST=piveau-hub
      - PIVEAU_HUB_PORT=8080
      - REPOSITORY=/ids/repo/
    ports:
      - 8092:8080